import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Box, Text } from '../atoms'
import { Footer } from '../organisms/layout/footer'
import { useAppContext } from '../context/AppContext'
import { useState } from 'react'
import { Banner } from '../components/banner/banner'
import { useMediaQuery, useTheme } from '@mui/material'
import { useRouter } from 'next/router'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

   const { setLoading, alert } = useAppContext()
   const router = useRouter()

   const [forms, setForms] = useState({})
   const widthLarge = useMediaQuery('(min-width:1536px)')

   const handleChange = (value) => {

      setForms((prevValues) => ({
         ...prevValues,
         [value.target.name]: value.target.value,
      }))
   }

   const theme = useTheme()
   const navBar = useMediaQuery(theme.breakpoints.down('md'))


   return (
      <>
         <Head>
            <title>LP Green4T - Conexão com Excelência</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
            <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
            <link rel="icon" href="/logo.png" />
         </Head>

         <Box fullWidth sx={styles.container}>
            <Box fullWidth sx={{ ...styles.containerSection }}>
               <Box sx={{ display: 'flex', width: '100%', height: { xs: 'auto', xm: 480, md: 480, lg: 735, xl: 968 }, }}>
                  <Box sx={{
                     position: 'absolute',
                     width: '100%',
                     height: { xs: 330, xm: 480, md: 480, lg: '100%' },
                     zIndex: 999,
                     display: 'flex',
                     alignItems: 'center',
                     justifyContent: 'center',
                  }}>
                     <Box
                        sx={{
                           display: 'flex',
                           alignItems: 'center',
                           justifyContent: 'center',
                           maxWidth: { xs: '90%', xm: '100%', md: '100%', lg: '100%' }
                        }}>
                        <Text bold veryLarge style={{ color: '#fff' }}>Conexão Excelência</Text>
                        <Text bold large style={{ color: '#fff' }}>O novo canal de Qualidade da green4t</Text>
                        <Text large style={{ color: '#fff' }}>Uma iniciativa pensada exclusivamente para você ter um meio direto de comunicação
                           com nossa equipe de qualidade</Text>
                        <Text large style={{ color: '#fff' }}>Aqui você pode compartilhar suas expêriencias, sugestões, dúvidas ou qualquer outro feedback
                           que deseje nos passar. Nossa equipe de Qualidade se dedicará a analisar e garantir um retorno breve e eficaz sobre suas contribuições. </Text>
                        <Text bold large style={{ color: '#fff' }}>Agradeçemos o contato</Text>
                     </Box>

                  </Box>
                  <Banner />
               </Box>

            </Box>

            <Footer />
         </Box >
      </>
   )
}

const styles = {
   container: {
      // backgroundColor: '#fff',
      flex: 1
   },
   containerSection: {
      backgroundColor: '#fff',
      // display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: { xs: 0, xm: 10, md: 10, lg: 0 },
      left: 0,
      width: '100%',
      height: 'auto'
   },
   textHeader: {
      color: '#fff'
   },
   imgGalery: {
      backgroundSize: { xs: `contain`, xm: 'contain', md: 'cover', lg: 'cover' },
      backgroundRepeat: 'no-repeat',
      // backgroundPosition: 'center center',
      // overflow: 'hidden',
      marginBottom: 3,
   },

}
